# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0147_merge_20181108_1643'),
        ('osf', '0142_remove_waffle_analytics_flags'),
    ]

    operations = [
    ]
