# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0149_merge_20181116_1852'),
        ('osf', '0146_merge_20181119_2236'),
    ]

    operations = [
    ]
