# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-03 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0150_merge_20181120_1541'),
        ('osf', '0146_update_registration_schemas'),
    ]

    operations = [
    ]
